name: Codespell

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'main') }}

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
          cache: pip
          cache-dependency-path: .github/workflows/codespell.yml

      - name: Install codespell
        run: python -m pip install --upgrade pip codespell

      - name: Run codespell
        run: |
          codespell \
            --config .codespellrc \
            --builtin clear,rare,informal,usage,code,names \
            --ignore-words .codespell/ignore.txt \
            --dictionary .codespell/dictionary.txt,-

      - name: Check codespell files are sorted
        if: ${{ always() }}
        shell: bash
        run: |
          for f in .codespell/dictionary.txt .codespell/ignore.txt; do
            LC_ALL=C sort -c "${f}"
          done
